version: "3"

services:
  onlyoffice-mysql-server:
    image: mysql:8.0.29
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    stdin_open: true
    tty: true
    restart: always
    volumes:
      - ./app/onlyoffice/mysql/conf.d:/etc/mysql/conf.d
      - ./app/onlyoffice/mysql/initdb:/docker-entrypoint-initdb.d
      - ./app/onlyoffice/mysql/mysql_data:/var/lib/mysql

  onlyoffice-community-server:
    image: onlyoffice/communityserver:${SOFTWARE_VERSION_TAG}
    environment:
      - ONLYOFFICE_CORE_MACHINEKEY=${ONLYOFFICE_CORE_MACHINEKEY}
      - CONTROL_PANEL_PORT_80_TCP=${CONTROL_PANEL_PORT_80_TCP}
      - CONTROL_PANEL_PORT_80_TCP_ADDR=${CONTROL_PANEL_PORT_80_TCP_ADDR}
      - MYSQL_SERVER_ROOT_PASSWORD=${MYSQL_SERVER_ROOT_PASSWORD}
      - MYSQL_SERVER_DB_NAME=${MYSQL_SERVER_DB_NAME}
      - MYSQL_SERVER_HOST=${MYSQL_SERVER_HOST}
      - MYSQL_SERVER_USER=${MYSQL_SERVER_USER}
      - MYSQL_SERVER_PASS=${MYSQL_SERVER_PASS}
      - ELASTICSEARCH_SERVER_HOST=${ELASTICSEARCH_SERVER_HOST}
      - ELASTICSEARCH_SERVER_HTTPPORT=${ELASTICSEARCH_SERVER_HTTPPORT}
      - DOCUMENT_SERVER_PORT_80_TCP_ADDR=onlyoffice-document-server
      - DOCUMENT_SERVER_JWT_ENABLED=true
      - DOCUMENT_SERVER_JWT_SECRET=jwt_secret
      - DOCUMENT_SERVER_JWT_HEADER=AuthorizationJwt
    ports:
      - "172.17.0.1:19543:80"
      - "5222:5222"
    stdin_open: true
    tty: true
    restart: always
    privileged: true
    cgroup: host
    volumes:
      - ./app/onlyoffice/CommunityServer/community_data:/var/www/onlyoffice/Data
      - ./app/onlyoffice/CommunityServer/community_log:/var/log/onlyoffice
      - ./app/onlyoffice/CommunityServer/community_letsencrypt:/etc/letsencrypt
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - ./app/onlyoffice/CommunityServer/certs:/var/www/onlyoffice/Data/certs
    depends_on:
      - onlyoffice-mysql-server
      - onlyoffice-elasticsearch

  onlyoffice-elasticsearch:
    image: onlyoffice/elasticsearch:7.16.3
    restart: always
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g -Dlog4j2.formatMsgNoLookups=true"
      - "indices.fielddata.cache.size=30%"
      - "indices.memory.index_buffer_size=30%"
      - "ingest.geoip.downloader.enabled=false"
    expose:
      - "9200"
      - "9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
    volumes:
      - ./es_data:/usr/share/elasticsearch/data

  onlyoffice-control-panel:
    image: onlyoffice/controlpanel:3.1.1.467
    environment:
      - ONLYOFFICE_CORE_MACHINEKEY=${ONLYOFFICE_CORE_MACHINEKEY}
    expose:
      - "80"
      - "443"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./app/controlpanel_data:/var/www/onlyoffice/Data
      - ./app/controlpanel_log:/var/log/onlyoffice
    stdin_open: true
    tty: true
    depends_on:
      - onlyoffice-community-server
      - onlyoffice-document-server

  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:$DOCUMENT_SERVER_VERSION_TAG
    stdin_open: true
    tty: true
    restart: always
    environment:
     - JWT_ENABLED=true
     - JWT_SECRET=jwt_secret
     - JWT_HEADER=AuthorizationJwt
    expose:
      - '80'
      - '443'
    volumes:
       - ./storage/document_data:/var/www/onlyoffice/Data
       - ./storage/document_log:/var/log/onlyoffice
       - ./document_fonts:/usr/share/fonts/truetype/custom
       - ./storage/document_forgotten:/var/lib/onlyoffice/documentserver/App_Data/cache/files/forgotten
